openapi: 3.0.3
info:
  title: System Manager API
servers:
  - url: http://localhost/api
tags:
  - name: Companies
paths:
  /companies:  
    get:
      tags:
        - Companies
      summary: Get all companies
      description: User can get all companies.
      responses:
        '200':
          description: successful operation
          content:
            schemas:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
              example:
              - id: 1
                name: Top level Electric
                created_at: '2023-10-18T07:27:02.000000Z'
                updated_at: '2023-10-20T06:52:10.000000Z'
              - id: 2
                name: Fast Charger Ltd
                created_at: '2023-10-18T07:27:02.000000Z'
                updated_at: '2023-10-18T07:27:02.000000Z'
              - id: 3
                name: Resource Ltd
                created_at: '2023-10-18T07:27:02.000000Z'
                updated_at: '2023-10-18T07:27:02.000000Z'     
    post:
      tags:
        - Companies
      summary: Add new company
      description: User can add a new company.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: Company Test
                  created_at:
                    type: string
                    example: 2023-10-18T17:41:33.000000Z
                  updated_at:
                    type: string
                    example: 2023-10-18T17:41:33.000000Z
  /companies/{id}:
    put:
      tags:
        - Companies
      summary: Update company
      description: User can update a company by id.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Company updated
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: Company updated
                  created_at:
                    type: string
                    example: 2023-10-18T17:41:33.000000Z
                  updated_at:
                    type: string
                    example: 2023-10-18T17:41:33.000000Z
    get:
      tags:
        - Companies
      summary: Get company
      description: User can get a company by id.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: Company updated
                  created_at:
                    type: string
                    example: 2023-10-18T17:41:33.000000Z
                  updated_at:
                    type: string
                    example: 2023-10-18T17:41:33.000000Z 
    delete:
        tags:
          - Companies
        summary: Delete company
        description: User can delete a company by id.
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Company was deleted.                  
components:
  schemas:
    Company:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: Company Test
    
  